/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AbstractProductA;

import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author mark
 */
public class MojPanel1 extends Panel {

    /**
     * Creates new form MojPanel1
     */
    public MojPanel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jTxtNaziv = new javax.swing.JTextField();
        jTxtIzdavac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAutori = new javax.swing.JTextArea();
        jBtnIzdaj = new javax.swing.JButton();
        jBtnDodaj = new javax.swing.JButton();
        jBtnObrisi = new javax.swing.JButton();
        jBtnIzmeni = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Datum = new datechooser.beans.DateChooserCombo();
        Poruka = new javax.swing.JTextField();

        jLabel4.setText("ID publikacije");

        jLabel1.setText("Naziv");

        jLabel2.setText("Izdavac");

        jLabel3.setText("Autori");

        jTxtAutori.setColumns(20);
        jTxtAutori.setRows(5);
        jScrollPane1.setViewportView(jTxtAutori);

        jBtnIzdaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/img/search-128.png"))); // NOI18N
        jBtnIzdaj.setToolTipText("Pretrazi po ID-ju");

        jBtnDodaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/img/add-128.png"))); // NOI18N
        jBtnDodaj.setToolTipText("Dodaj novu publikaciju");

        jBtnObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/img/61391.png"))); // NOI18N
        jBtnObrisi.setToolTipText("Obrisi trenutnu publikaciju");

        jBtnIzmeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/img/edit.png"))); // NOI18N
        jBtnIzmeni.setToolTipText("Izmeni publikaciju");

        jLabel5.setText("Datum izdavanja");

        Poruka.setForeground(new java.awt.Color(255, 0, 0));
        Poruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorukaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnIzdaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jBtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNaziv)
                            .addComponent(jTxtIzdavac)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Poruka, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnIzdaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIzdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Datum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Poruka, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorukaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo Datum;
    private javax.swing.JTextField Poruka;
    private javax.swing.JButton jBtnDodaj;
    private javax.swing.JButton jBtnIzdaj;
    private javax.swing.JButton jBtnIzmeni;
    private javax.swing.JButton jBtnObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtAutori;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtIzdavac;
    private javax.swing.JTextField jTxtNaziv;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getIDKnjige() {
        return jTxtID.getText().trim();
    }

    @Override
    public JTextField getIDKnjige1() {
        return jTxtID;
    }

    @Override
    public String getNaziv() {
        return jTxtNaziv.getText().trim();
    }

    @Override
    public String getIzdavac() {
        return jTxtIzdavac.getText().trim();
    }

    @Override
    public String getAutori() {
        return jTxtAutori.getText().trim();
    }

    @Override
    public Date getDatum() {
        return Datum.getSelectedDate().getTime();
    }

    @Override
    public void setIDKnjige(String id) {
        jTxtID.setText(id);
    }

    @Override
    public void setNaziv(String naziv) {
        jTxtNaziv.setText(naziv);
    }

    @Override
    public void setIzdavac(String izdavac) {
        jTxtIzdavac.setText(izdavac);
    }

    @Override
    public void setAutori(String autori) {
        jTxtAutori.setText(autori);
    }

    @Override
    public void setDatum(Date Datum1) {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(Datum1);
        Datum.setSelectedDate(gc);
    }

    @Override
    public void setPoruka(String Poruka1) {
        Poruka.setText(Poruka1);
    }

    @Override
    public JButton getDodaj() {
        return jBtnDodaj;
    }

    @Override
    public JButton getIzmeni() {
        return jBtnIzmeni;
    }

    @Override
    public JButton getObrisi() {
        return jBtnObrisi;
    }

    @Override
    public JButton getIzdaj() {
        return jBtnIzdaj;
    }
}
